---
- hosts: master
  remote_user: sudo-user
  vars:
    src_path: "."
#    proxy_host: "http://proxy"
#    proxy_port: "8080"

  tasks:
    - name: upgrade all packages
      yum: name=* state=latest

    - name: groupinstall
      yum: name="@Development Tools" state=latest

    - name: ntp & ntpdate yum install
      yum: name="{{ item }}" state=latest
      with_items:
        - ntp
        - ntpdate

    - name: mesos rpm install
      # shell: "rpm --httpproxy {{ proxy_host }} --httpport {{ proxy_port }} -Uvh http://repos.mesosphere.com/el/6/noarch/RPMS/mesosphere-el-repo-6-2.noarch.rpm"
      shell: "rpm -Uvh http://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-3.noarch.rpm"
      ignore_errors: yes

    - name: mesos yum install
      yum: name="{{ item }}" state=latest
      with_items:
        - mesos
        - marathon
        - chronos
        - mesosphere-zookeeper

    - name: install libselinux-python 
      yum: name=libselinux-python state=installed

    - name: copy zookeeper myid 
      template: src="{{ src_path }}/{{ inventory_hostname }}.myid" dest=/var/lib/zookeeper/myid owner=root group=root mode=644

    - name: copy zoo.cfg
      copy: src="{{ src_path }}/zoo.cfg" dest=/etc/zookeeper/conf/zoo.cfg owner=root group=root mode=644
      
    - name: copy clouster file
      copy: src="{{ src_path }}/cluster" dest=/etc/mesos-master/cluster owner=root group=root mode=644

    - name: copy zk file
      copy: src="{{ src_path }}/zk" dest=/etc/mesos/zk owner=root group=root mode=644

    - name: copy quorum file
      copy: src="{{ src_path }}/quorum" dest=/etc/mesos-master/quorum owner=root group=root mode=644

    - name: copy hostname file
      template: src="{{ src_path }}/hostname" dest=/etc/mesos-master/hostname owner=root group=root mode=644

    - name: copy hostname file
      template: src="{{ src_path }}/hostname" dest=/etc/hostname owner=root group=root mode=644

    - name: stop firewalld
      service: name=firewalld enabled=false state=stopped

    - name: install epel
      yum: name=epel-release state=latest
      ignore_errors: yes

    - name: disable seLinux
      selinux: state=disabled

    - name: mesos-slave stop
      service: name=mesos-slave enabled=false state=stopped

    - name: zookeeper-server start
      service: name=zookeeper enabled=true state=restarted

    - name: mesos-master start
      service: name=mesos-master enabled=true state=restarted

    - name: marathon start
      service: name=marathon enabled=true state=restarted

    - name: chronos start
      service: name=chronos enabled=true state=restarted

    - name: reboot
      shell: reboot
      async: 0
      poll: 0
      ignore_errors: yes
