---
- hosts: slave
  remote_user: sudo-user
  vars:
    src_path: "."
#    proxy_host: "http://proxy"
#    proxy_port: "8080"

  tasks:
    - name: upgrade all packages
      yum: name=* state=latest

    - name: groupinstall
      yum: name="@Development Tools" state=latest

    - name: ntp & ntpdate yum install
      yum: name="{{ item }}" state=latest
      with_items:
        - ntp
        - ntpdate

    - name: mesos rpm install
      # shell: "rpm --httpproxy {{ proxy_host }} --httpport {{ proxy_port }} -Uvh http://repos.mesosphere.com/el/6/noarch/RPMS/mesosphere-el-repo-6-2.noarch.rpm"
      shell: "rpm -Uvh http://repos.mesosphere.io/el/7/noarch/RPMS/mesosphere-el-repo-7-3.noarch.rpm"
      ignore_errors: yes

    - name: mesos yum install
      yum: name="{{ item }}" state=latest
      with_items:
        - mesos

    - name: install libselinux-python 
      yum: name=libselinux-python state=installed

    - name: copy zk file
      copy: src="{{ src_path }}/zk" dest=/etc/mesos/zk owner=root group=root mode=644

    - name: copy hostname file
      template: src="{{ src_path }}/hostname" dest=/etc/hostname owner=root group=root mode=644

    - name: stop firewalld
      service: name=firewalld enabled=false state=stopped

    - name: install epel
      yum: name=epel-release state=latest
      ignore_errors: yes

    - name: disable seLinux
      selinux: state=disabled

    - name: mesos-master stop
      service: name=mesos-master enabled=false state=stopped

    - name: mesos-slave start
      service: name=mesos-slave enabled=true state=restarted

    - name: reboot
      shell: reboot
      async: 0
      poll: 0
      ignore_errors: yes
